### ISSUE TITLE
same name with yours 

### ISSUE THREAD

**Issue by ChunelFeng** [dlitviniuc/CGraph#1]
Hi, my repo has same name with you: 

 https://github.com/ChunelFeng/CGraph

hah, nice to meet you

**Comment by dlitviniuc** [comment]
hi, do you want me to change the name? it's a simple uni project and it doesn't matter to me much

**Comment by ChunelFeng** [comment]
nonono, just say hello to you for the same name repo, hahaha

**Comment by dlitviniuc** [comment]
lol, ok, hello to you too name neighbour
